spring.application.name=DiplomaAnahit
spring.datasource.url=jdbc:mysql://localhost:13306/diploma
spring.datasource.password=ANAHIT
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.open-in-view=true
spring.security.user.name=username
spring.security.user.password=your-password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true


security.token.header=X-AUTH-TOKEN
security.token.secret=+Nre88DjS#Vb1Hs
security.token.expiration=3600

# refresh token
security.refreshtoken.header=REFRESH-TOKEN
security.refreshtoken.secret=oQ3KwDI8lI2sr5Hv7UgHHev88UWMvdy0
security.refreshtoken.expiration=864000
