spring.application.name=DiplomaAnahit

spring.datasource.url=jdbc:mysql://localhost:13306/diploma
spring.datasource.password=ANAHIT
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true


security.token.header=X-AUTH-TOKEN
security.token.secret=javaxsdfghjkjhgfdsxdcfvbgnhjmnbvcxzcvbnmnbvcxzcvbnmbvcxzcvbnmbvcxzcvbnmbvcxvbnmbvcxcvbn 
security.token.expiration=3600



springdoc.packages-to-scan=com.example.diplomaanahit.controllers
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.auto-tag-classes=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=polytecnicdiplomaanita@gmail.com
spring.mail.password=dlc2 zqln ikuw pqj5 q6mr 4myn zfuq ko6c
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
